# see https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
name: Build and Publish Image

on:
  push:
    branches: ['main']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta # needed to reference output tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
    
  update-cd-config:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout config repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}-config
          ref: main
          token: ${{ secrets.CONFIG_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
      
      - name: Update deployment image
        run: |
          echo setting kustomize image to ${{ needs.build-and-push-image.outputs.tag }}
          cd website
          kustomize edit set image ${{ needs.build-and-push-image.outputs.tag }}
          cat kustomization.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        

      
          